#############################################################################
# Makefile for building: xIrc
# Generated by qmake (1.07a) (Qt 3.3.3) on: Thu Jun 16 21:34:20 2022
# Project:  xIrc.pro
# Template: app
# Command: $(QMAKE) -o Makefile xIrc.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -m32 -march=i386 -mtune=pentium4  -DQT2 -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -std=c++98 -Wall -W -O2 -g -pipe -m32 -march=i386 -mtune=pentium4 -fpermissive -DQT2 -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib/qt-3.3/mkspecs/default -I. -IlibX++ -I$(QTDIR)/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lX++ -L./libX++ -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = ircreply.h \
		xIrcBanDialog.h \
		xIrcChannelQuery.h \
		xIrcChanNickBox.h \
		xIrcCommands.h \
		xIrcConnectDialog.h \
		xIrcConnect.h \
		xIrcDccChatFrame.h \
		xIrcDccFile.h \
		xIrcDccQuery.h \
		xIrcDccSocket.h \
		xIrcIgnoreQuery.h \
		xIrcInviteBox.h \
		xIrcLineEditQuery.h \
		xIrcMircServerParse.h \
		xIrcMsgDispatchEntry.h \
		xIrcMsgDispatch.h \
		xIrcMsgFrame.h \
		xIrcMsgQuery.h \
		xIrcNickActionQuery.h \
		xIrcNickCombo.h \
		xIrcNickListEntry.h \
		xIrcNickList.h \
		xIrcNickQuery.h \
		xIrcNotifyQuery.h \
		xIrcNotifyTable.h \
		xIrcPeopleEdit.h \
		xIrcPeopleEntry.h \
		xIrcPeopleList.h \
		xIrcPeopleTable.h \
		xIrcServerEdit.h \
		xIrcServerEntry.h \
		xIrcServerList.h \
		xIrcServerQuery.h \
		xIrcServerTable.h \
		xIrcSocket.h
SOURCES = xIrc.cpp \
		xIrcBanDialog.cpp \
		xIrcChannelQuery.cpp \
		xIrcChanNickBox.cpp \
		xIrcCommands.cpp \
		xIrcConnect1.cpp \
		xIrcConnect2.cpp \
		xIrcConnect3.cpp \
		xIrcConnectDialog.cpp \
		xIrcDccChatFrame.cpp \
		xIrcDccFile.cpp \
		xIrcDccQuery.cpp \
		xIrcDccSocket.cpp \
		xIrcIgnoreQuery.cpp \
		xIrcInviteBox.cpp \
		xIrcMircServerParse.cpp \
		xIrcMsgDispatch.cpp \
		xIrcMsgDispatchEntry.cpp \
		xIrcMsgFrame1.cpp \
		xIrcMsgFrame2.cpp \
		xIrcMsgQuery.cpp \
		xIrcNickActionQuery.cpp \
		xIrcNickCombo.cpp \
		xIrcNickList.cpp \
		xIrcNickListEntry.cpp \
		xIrcNickQuery.cpp \
		xIrcNotifyQuery.cpp \
		xIrcNotifyTable.cpp \
		xIrcPeopleEdit.cpp \
		xIrcPeopleEntry.cpp \
		xIrcPeopleList.cpp \
		xIrcPeopleTable.cpp \
		xIrcServerEdit.cpp \
		xIrcServerEntry.cpp \
		xIrcServerList.cpp \
		xIrcServerQuery.cpp \
		xIrcServerTable.cpp \
		xIrcSocket.cpp
OBJECTS = xIrc.o \
		xIrcBanDialog.o \
		xIrcChannelQuery.o \
		xIrcChanNickBox.o \
		xIrcCommands.o \
		xIrcConnect1.o \
		xIrcConnect2.o \
		xIrcConnect3.o \
		xIrcConnectDialog.o \
		xIrcDccChatFrame.o \
		xIrcDccFile.o \
		xIrcDccQuery.o \
		xIrcDccSocket.o \
		xIrcIgnoreQuery.o \
		xIrcInviteBox.o \
		xIrcMircServerParse.o \
		xIrcMsgDispatch.o \
		xIrcMsgDispatchEntry.o \
		xIrcMsgFrame1.o \
		xIrcMsgFrame2.o \
		xIrcMsgQuery.o \
		xIrcNickActionQuery.o \
		xIrcNickCombo.o \
		xIrcNickList.o \
		xIrcNickListEntry.o \
		xIrcNickQuery.o \
		xIrcNotifyQuery.o \
		xIrcNotifyTable.o \
		xIrcPeopleEdit.o \
		xIrcPeopleEntry.o \
		xIrcPeopleList.o \
		xIrcPeopleTable.o \
		xIrcServerEdit.o \
		xIrcServerEntry.o \
		xIrcServerList.o \
		xIrcServerQuery.o \
		xIrcServerTable.o \
		xIrcSocket.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_xIrcBanDialog.cpp \
		moc_xIrcChannelQuery.cpp \
		moc_xIrcChanNickBox.cpp \
		moc_xIrcConnectDialog.cpp \
		moc_xIrcConnect.cpp \
		moc_xIrcDccChatFrame.cpp \
		moc_xIrcDccFile.cpp \
		moc_xIrcDccQuery.cpp \
		moc_xIrcDccSocket.cpp \
		moc_xIrcIgnoreQuery.cpp \
		moc_xIrcInviteBox.cpp \
		moc_xIrcMsgDispatchEntry.cpp \
		moc_xIrcMsgFrame.cpp \
		moc_xIrcMsgQuery.cpp \
		moc_xIrcNickActionQuery.cpp \
		moc_xIrcNickCombo.cpp \
		moc_xIrcNickQuery.cpp \
		moc_xIrcNotifyQuery.cpp \
		moc_xIrcNotifyTable.cpp \
		moc_xIrcPeopleEdit.cpp \
		moc_xIrcPeopleTable.cpp \
		moc_xIrcServerEdit.cpp \
		moc_xIrcServerQuery.cpp \
		moc_xIrcServerTable.cpp \
		moc_xIrcSocket.cpp
OBJMOC = moc_xIrcBanDialog.o \
		moc_xIrcChannelQuery.o \
		moc_xIrcChanNickBox.o \
		moc_xIrcConnectDialog.o \
		moc_xIrcConnect.o \
		moc_xIrcDccChatFrame.o \
		moc_xIrcDccFile.o \
		moc_xIrcDccQuery.o \
		moc_xIrcDccSocket.o \
		moc_xIrcIgnoreQuery.o \
		moc_xIrcInviteBox.o \
		moc_xIrcMsgDispatchEntry.o \
		moc_xIrcMsgFrame.o \
		moc_xIrcMsgQuery.o \
		moc_xIrcNickActionQuery.o \
		moc_xIrcNickCombo.o \
		moc_xIrcNickQuery.o \
		moc_xIrcNotifyQuery.o \
		moc_xIrcNotifyTable.o \
		moc_xIrcPeopleEdit.o \
		moc_xIrcPeopleTable.o \
		moc_xIrcServerEdit.o \
		moc_xIrcServerQuery.o \
		moc_xIrcServerTable.o \
		moc_xIrcSocket.o
DIST	   = xIrc.pro
QMAKE_TARGET = xIrc
DESTDIR  = 
TARGET   = xIrc

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: xIrc.pro  /usr/lib/qt-3.3/mkspecs/default/qmake.conf /usr/lib/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile xIrc.pro
qmake: 
	@$(QMAKE) -o Makefile xIrc.pro

dist: 
	@mkdir -p .tmp/xIrc && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/xIrc/ && ( cd `dirname .tmp/xIrc` && $(TAR) xIrc.tar xIrc && $(GZIP) xIrc.tar ) && $(MOVE) `dirname .tmp/xIrc`/xIrc.tar.gz . && $(DEL_FILE) -r .tmp/xIrc

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

xIrc.o: xIrc.cpp xIrcConnect.h \
		xIrcMsgDispatch.h \
		xIrcNickQuery.h \
		xIrcNickCombo.h \
		xIrcLineEditQuery.h \
		xIrcServerQuery.h \
		xIrcChannelQuery.h \
		xIrcSocket.h \
		xIrcMsgFrame.h \
		xIrcIgnoreQuery.h \
		xIrcNotifyQuery.h \
		xIrcNotifyTable.h \
		xIrcCommands.h \
		xIrcMsgQuery.h \
		xIrcDccChatFrame.h \
		xIrcDccFile.h \
		xIrcNickActionQuery.h \
		xIrcBanDialog.h \
		xIrcChanNickBox.h \
		xIrcNickList.h \
		xIrcNickListEntry.h \
		xIrcConnectDialog.h \
		xIrcPeopleTable.h \
		xIrcServerEntry.h \
		xIrcPeopleList.h \
		xIrcPeopleEntry.h \
		xIrcDccSocket.h \
		xIrcMsgDispatchEntry.h \
		xIrcServerTable.h \
		xIrcServerList.h

xIrcBanDialog.o: xIrcBanDialog.cpp xIrcBanDialog.h

xIrcChannelQuery.o: xIrcChannelQuery.cpp xIrcChannelQuery.h \
		xIrcCommands.h \
		xIrcSocket.h

xIrcChanNickBox.o: xIrcChanNickBox.cpp xIrcChanNickBox.h \
		xIrcNickCombo.h \
		xIrcNickList.h \
		xIrcNickListEntry.h

xIrcCommands.o: xIrcCommands.cpp xIrcCommands.h

xIrcConnect1.o: xIrcConnect1.cpp xIrcChannelQuery.h \
		xIrcLineEditQuery.h \
		xIrcMsgDispatch.h \
		xIrcNickQuery.h \
		xIrcDccQuery.h \
		xIrcServerQuery.h \
		xIrcInviteBox.h \
		xIrcIgnoreQuery.h \
		xIrcConnect.h \
		xIrcSocket.h \
		xIrcMsgDispatchEntry.h \
		xIrcConnectDialog.h \
		xIrcServerTable.h \
		xIrcServerEntry.h \
		xIrcServerList.h \
		xIrcPeopleTable.h \
		xIrcPeopleList.h \
		xIrcPeopleEntry.h \
		xIrcMsgFrame.h \
		xIrcNotifyQuery.h \
		xIrcNotifyTable.h \
		xIrcCommands.h \
		xIrcMsgQuery.h \
		xIrcDccChatFrame.h \
		xIrcDccFile.h \
		xIrcNickActionQuery.h \
		xIrcBanDialog.h \
		xIrcChanNickBox.h \
		xIrcNickCombo.h \
		xIrcNickList.h \
		xIrcNickListEntry.h \
		xIrcDccSocket.h

xIrcConnect2.o: xIrcConnect2.cpp xIrcLineEditQuery.h \
		xIrcChannelQuery.h \
		xIrcMsgDispatch.h \
		xIrcDccQuery.h \
		xIrcServerQuery.h \
		xIrcInviteBox.h \
		xIrcConnect.h \
		xIrcSocket.h \
		xIrcMsgDispatchEntry.h \
		xIrcConnectDialog.h \
		xIrcServerTable.h \
		xIrcServerEntry.h \
		xIrcServerList.h \
		xIrcMsgFrame.h \
		xIrcIgnoreQuery.h \
		xIrcNotifyQuery.h \
		xIrcNotifyTable.h \
		xIrcCommands.h \
		xIrcMsgQuery.h \
		xIrcDccChatFrame.h \
		xIrcDccFile.h \
		xIrcNickActionQuery.h \
		xIrcBanDialog.h \
		xIrcChanNickBox.h \
		xIrcNickCombo.h \
		xIrcNickList.h \
		xIrcNickListEntry.h \
		xIrcPeopleTable.h \
		xIrcPeopleList.h \
		xIrcPeopleEntry.h \
		xIrcDccSocket.h

xIrcConnect3.o: xIrcConnect3.cpp xIrcCommands.h \
		xIrcLineEditQuery.h \
		xIrcMsgDispatch.h \
		xIrcPeopleEdit.h \
		xIrcPeopleEntry.h \
		xIrcConnect.h \
		xIrcSocket.h \
		xIrcMsgDispatchEntry.h \
		xIrcMsgFrame.h \
		xIrcIgnoreQuery.h \
		xIrcNotifyQuery.h \
		xIrcNotifyTable.h \
		xIrcMsgQuery.h \
		xIrcDccChatFrame.h \
		xIrcDccFile.h \
		xIrcNickActionQuery.h \
		xIrcBanDialog.h \
		xIrcChanNickBox.h \
		xIrcNickCombo.h \
		xIrcNickList.h \
		xIrcNickListEntry.h \
		xIrcConnectDialog.h \
		xIrcPeopleTable.h \
		xIrcServerEntry.h \
		xIrcPeopleList.h \
		xIrcDccSocket.h

xIrcConnectDialog.o: xIrcConnectDialog.cpp xIrcConnectDialog.h \
		xIrcServerEntry.h

xIrcDccChatFrame.o: xIrcDccChatFrame.cpp xIrcLineEditQuery.h \
		xIrcSocket.h \
		xIrcDccChatFrame.h \
		xIrcDccSocket.h

xIrcDccFile.o: xIrcDccFile.cpp xIrcLineEditQuery.h \
		xIrcDccFile.h \
		xIrcSocket.h \
		xIrcDccSocket.h

xIrcDccQuery.o: xIrcDccQuery.cpp xIrcDccQuery.h \
		xIrcSocket.h

xIrcDccSocket.o: xIrcDccSocket.cpp xIrcDccSocket.h

xIrcIgnoreQuery.o: xIrcIgnoreQuery.cpp xIrcPeopleEdit.h \
		xIrcIgnoreQuery.h \
		xIrcPeopleEntry.h \
		xIrcSocket.h \
		xIrcConnectDialog.h \
		xIrcPeopleTable.h \
		xIrcServerEntry.h \
		xIrcPeopleList.h

xIrcInviteBox.o: xIrcInviteBox.cpp xIrcInviteBox.h \
		xIrcSocket.h

xIrcMircServerParse.o: xIrcMircServerParse.cpp xIrcServerList.h \
		xIrcServerEntry.h

xIrcMsgDispatch.o: xIrcMsgDispatch.cpp ircreply.h \
		xIrcMsgDispatch.h \
		xIrcSocket.h \
		xIrcMsgDispatchEntry.h

xIrcMsgDispatchEntry.o: xIrcMsgDispatchEntry.cpp ircreply.h \
		xIrcCommands.h \
		xIrcMsgDispatchEntry.h \
		xIrcSocket.h

xIrcMsgFrame1.o: xIrcMsgFrame1.cpp xIrcMsgDispatch.h \
		xIrcMsgFrame.h \
		xIrcNickQuery.h \
		xIrcSocket.h \
		xIrcMsgDispatchEntry.h \
		xIrcCommands.h \
		xIrcChanNickBox.h \
		xIrcNickCombo.h \
		xIrcNickList.h \
		xIrcNickListEntry.h

xIrcMsgFrame2.o: xIrcMsgFrame2.cpp xIrcNickQuery.h \
		xIrcLineEditQuery.h \
		xIrcMsgDispatch.h \
		xIrcMsgFrame.h \
		xIrcChannelQuery.h \
		xIrcSocket.h \
		xIrcMsgDispatchEntry.h \
		xIrcCommands.h \
		xIrcChanNickBox.h \
		xIrcNickCombo.h \
		xIrcNickList.h \
		xIrcNickListEntry.h

xIrcMsgQuery.o: xIrcMsgQuery.cpp xIrcMsgQuery.h \
		xIrcSocket.h

xIrcNickActionQuery.o: xIrcNickActionQuery.cpp xIrcNickActionQuery.h

xIrcNickCombo.o: xIrcNickCombo.cpp xIrcNickCombo.h \
		xIrcNickList.h \
		xIrcNickListEntry.h

xIrcNickList.o: xIrcNickList.cpp xIrcNickList.h \
		xIrcNickListEntry.h

xIrcNickListEntry.o: xIrcNickListEntry.cpp xIrcNickListEntry.h

xIrcNickQuery.o: xIrcNickQuery.cpp xIrcNickQuery.h \
		xIrcSocket.h

xIrcNotifyQuery.o: xIrcNotifyQuery.cpp xIrcCommands.h \
		xIrcConnect.h \
		xIrcMsgDispatch.h \
		xIrcNotifyQuery.h \
		xIrcPeopleEdit.h \
		xIrcSocket.h \
		xIrcMsgFrame.h \
		xIrcIgnoreQuery.h \
		xIrcNotifyTable.h \
		xIrcMsgQuery.h \
		xIrcDccChatFrame.h \
		xIrcDccFile.h \
		xIrcNickActionQuery.h \
		xIrcBanDialog.h \
		xIrcChanNickBox.h \
		xIrcNickCombo.h \
		xIrcNickList.h \
		xIrcNickListEntry.h \
		xIrcConnectDialog.h \
		xIrcPeopleTable.h \
		xIrcServerEntry.h \
		xIrcPeopleList.h \
		xIrcPeopleEntry.h \
		xIrcDccSocket.h \
		xIrcMsgDispatchEntry.h

xIrcNotifyTable.o: xIrcNotifyTable.cpp xIrcCommands.h \
		xIrcConnect.h \
		xIrcMsgDispatch.h \
		xIrcNotifyTable.h \
		xIrcPeopleEdit.h \
		xIrcSocket.h \
		xIrcMsgFrame.h \
		xIrcIgnoreQuery.h \
		xIrcNotifyQuery.h \
		xIrcMsgQuery.h \
		xIrcDccChatFrame.h \
		xIrcDccFile.h \
		xIrcNickActionQuery.h \
		xIrcBanDialog.h \
		xIrcChanNickBox.h \
		xIrcNickCombo.h \
		xIrcNickList.h \
		xIrcNickListEntry.h \
		xIrcConnectDialog.h \
		xIrcPeopleTable.h \
		xIrcServerEntry.h \
		xIrcPeopleList.h \
		xIrcPeopleEntry.h \
		xIrcDccSocket.h \
		xIrcMsgDispatchEntry.h

xIrcPeopleEdit.o: xIrcPeopleEdit.cpp xIrcPeopleEdit.h \
		xIrcPeopleEntry.h \
		xIrcSocket.h

xIrcPeopleEntry.o: xIrcPeopleEntry.cpp xIrcConnect.h \
		xIrcPeopleEntry.h \
		xIrcSocket.h \
		xIrcMsgFrame.h \
		xIrcIgnoreQuery.h \
		xIrcNotifyQuery.h \
		xIrcNotifyTable.h \
		xIrcCommands.h \
		xIrcMsgQuery.h \
		xIrcDccChatFrame.h \
		xIrcDccFile.h \
		xIrcNickActionQuery.h \
		xIrcBanDialog.h \
		xIrcChanNickBox.h \
		xIrcNickCombo.h \
		xIrcNickList.h \
		xIrcNickListEntry.h \
		xIrcConnectDialog.h \
		xIrcPeopleTable.h \
		xIrcServerEntry.h \
		xIrcPeopleList.h \
		xIrcDccSocket.h

xIrcPeopleList.o: xIrcPeopleList.cpp xIrcPeopleList.h \
		xIrcPeopleEntry.h \
		xIrcSocket.h

xIrcPeopleTable.o: xIrcPeopleTable.cpp xIrcPeopleTable.h \
		xIrcPeopleList.h \
		xIrcPeopleEntry.h \
		xIrcSocket.h

xIrcServerEdit.o: xIrcServerEdit.cpp xIrcServerEdit.h \
		xIrcServerEntry.h

xIrcServerEntry.o: xIrcServerEntry.cpp xIrcServerEntry.h

xIrcServerList.o: xIrcServerList.cpp xIrcServerList.h \
		xIrcServerEntry.h

xIrcServerQuery.o: xIrcServerQuery.cpp xIrcServerEdit.h \
		xIrcServerQuery.h \
		xIrcServerEntry.h \
		xIrcConnectDialog.h \
		xIrcServerTable.h \
		xIrcSocket.h \
		xIrcServerList.h

xIrcServerTable.o: xIrcServerTable.cpp xIrcMircServerParse.h \
		xIrcServerTable.h \
		xIrcServerList.h \
		xIrcServerEntry.h

xIrcSocket.o: xIrcSocket.cpp xIrcCommands.h \
		xIrcSocket.h

moc_xIrcBanDialog.o: moc_xIrcBanDialog.cpp  xIrcBanDialog.h 

moc_xIrcChannelQuery.o: moc_xIrcChannelQuery.cpp  xIrcChannelQuery.h xIrcSocket.h

moc_xIrcChanNickBox.o: moc_xIrcChanNickBox.cpp  xIrcChanNickBox.h xIrcNickCombo.h \
		xIrcNickList.h \
		xIrcNickListEntry.h

moc_xIrcConnectDialog.o: moc_xIrcConnectDialog.cpp  xIrcConnectDialog.h xIrcServerEntry.h

moc_xIrcConnect.o: moc_xIrcConnect.cpp  xIrcConnect.h xIrcSocket.h \
		xIrcMsgFrame.h \
		xIrcIgnoreQuery.h \
		xIrcNotifyQuery.h \
		xIrcNotifyTable.h \
		xIrcCommands.h \
		xIrcMsgQuery.h \
		xIrcDccChatFrame.h \
		xIrcDccFile.h \
		xIrcNickActionQuery.h \
		xIrcBanDialog.h \
		xIrcChanNickBox.h \
		xIrcNickCombo.h \
		xIrcNickList.h \
		xIrcNickListEntry.h \
		xIrcConnectDialog.h \
		xIrcPeopleTable.h \
		xIrcServerEntry.h \
		xIrcPeopleList.h \
		xIrcPeopleEntry.h \
		xIrcDccSocket.h

moc_xIrcDccChatFrame.o: moc_xIrcDccChatFrame.cpp  xIrcDccChatFrame.h xIrcDccSocket.h

moc_xIrcDccFile.o: moc_xIrcDccFile.cpp  xIrcDccFile.h xIrcDccSocket.h

moc_xIrcDccQuery.o: moc_xIrcDccQuery.cpp  xIrcDccQuery.h xIrcSocket.h

moc_xIrcDccSocket.o: moc_xIrcDccSocket.cpp  xIrcDccSocket.h 

moc_xIrcIgnoreQuery.o: moc_xIrcIgnoreQuery.cpp  xIrcIgnoreQuery.h xIrcConnectDialog.h \
		xIrcPeopleTable.h \
		xIrcSocket.h \
		xIrcServerEntry.h \
		xIrcPeopleList.h \
		xIrcPeopleEntry.h

moc_xIrcInviteBox.o: moc_xIrcInviteBox.cpp  xIrcInviteBox.h xIrcSocket.h

moc_xIrcMsgDispatchEntry.o: moc_xIrcMsgDispatchEntry.cpp  xIrcMsgDispatchEntry.h xIrcSocket.h

moc_xIrcMsgFrame.o: moc_xIrcMsgFrame.cpp  xIrcMsgFrame.h xIrcSocket.h \
		xIrcCommands.h \
		xIrcChanNickBox.h \
		xIrcNickCombo.h \
		xIrcNickList.h \
		xIrcNickListEntry.h

moc_xIrcMsgQuery.o: moc_xIrcMsgQuery.cpp  xIrcMsgQuery.h xIrcSocket.h

moc_xIrcNickActionQuery.o: moc_xIrcNickActionQuery.cpp  xIrcNickActionQuery.h 

moc_xIrcNickCombo.o: moc_xIrcNickCombo.cpp  xIrcNickCombo.h xIrcNickList.h \
		xIrcNickListEntry.h

moc_xIrcNickQuery.o: moc_xIrcNickQuery.cpp  xIrcNickQuery.h xIrcSocket.h

moc_xIrcNotifyQuery.o: moc_xIrcNotifyQuery.cpp  xIrcNotifyQuery.h xIrcConnectDialog.h \
		xIrcPeopleTable.h \
		xIrcSocket.h \
		xIrcServerEntry.h \
		xIrcPeopleList.h \
		xIrcPeopleEntry.h

moc_xIrcNotifyTable.o: moc_xIrcNotifyTable.cpp  xIrcNotifyTable.h xIrcPeopleTable.h \
		xIrcPeopleList.h \
		xIrcPeopleEntry.h \
		xIrcSocket.h

moc_xIrcPeopleEdit.o: moc_xIrcPeopleEdit.cpp  xIrcPeopleEdit.h xIrcPeopleEntry.h \
		xIrcSocket.h

moc_xIrcPeopleTable.o: moc_xIrcPeopleTable.cpp  xIrcPeopleTable.h xIrcPeopleList.h \
		xIrcPeopleEntry.h \
		xIrcSocket.h

moc_xIrcServerEdit.o: moc_xIrcServerEdit.cpp  xIrcServerEdit.h xIrcServerEntry.h

moc_xIrcServerQuery.o: moc_xIrcServerQuery.cpp  xIrcServerQuery.h xIrcConnectDialog.h \
		xIrcServerTable.h \
		xIrcSocket.h \
		xIrcServerEntry.h \
		xIrcServerList.h

moc_xIrcServerTable.o: moc_xIrcServerTable.cpp  xIrcServerTable.h xIrcServerList.h \
		xIrcServerEntry.h

moc_xIrcSocket.o: moc_xIrcSocket.cpp  xIrcSocket.h 

moc_xIrcBanDialog.cpp: $(MOC) xIrcBanDialog.h
	$(MOC) xIrcBanDialog.h -o moc_xIrcBanDialog.cpp

moc_xIrcChannelQuery.cpp: $(MOC) xIrcChannelQuery.h
	$(MOC) xIrcChannelQuery.h -o moc_xIrcChannelQuery.cpp

moc_xIrcChanNickBox.cpp: $(MOC) xIrcChanNickBox.h
	$(MOC) xIrcChanNickBox.h -o moc_xIrcChanNickBox.cpp

moc_xIrcConnectDialog.cpp: $(MOC) xIrcConnectDialog.h
	$(MOC) xIrcConnectDialog.h -o moc_xIrcConnectDialog.cpp

moc_xIrcConnect.cpp: $(MOC) xIrcConnect.h
	$(MOC) xIrcConnect.h -o moc_xIrcConnect.cpp

moc_xIrcDccChatFrame.cpp: $(MOC) xIrcDccChatFrame.h
	$(MOC) xIrcDccChatFrame.h -o moc_xIrcDccChatFrame.cpp

moc_xIrcDccFile.cpp: $(MOC) xIrcDccFile.h
	$(MOC) xIrcDccFile.h -o moc_xIrcDccFile.cpp

moc_xIrcDccQuery.cpp: $(MOC) xIrcDccQuery.h
	$(MOC) xIrcDccQuery.h -o moc_xIrcDccQuery.cpp

moc_xIrcDccSocket.cpp: $(MOC) xIrcDccSocket.h
	$(MOC) xIrcDccSocket.h -o moc_xIrcDccSocket.cpp

moc_xIrcIgnoreQuery.cpp: $(MOC) xIrcIgnoreQuery.h
	$(MOC) xIrcIgnoreQuery.h -o moc_xIrcIgnoreQuery.cpp

moc_xIrcInviteBox.cpp: $(MOC) xIrcInviteBox.h
	$(MOC) xIrcInviteBox.h -o moc_xIrcInviteBox.cpp

moc_xIrcMsgDispatchEntry.cpp: $(MOC) xIrcMsgDispatchEntry.h
	$(MOC) xIrcMsgDispatchEntry.h -o moc_xIrcMsgDispatchEntry.cpp

moc_xIrcMsgFrame.cpp: $(MOC) xIrcMsgFrame.h
	$(MOC) xIrcMsgFrame.h -o moc_xIrcMsgFrame.cpp

moc_xIrcMsgQuery.cpp: $(MOC) xIrcMsgQuery.h
	$(MOC) xIrcMsgQuery.h -o moc_xIrcMsgQuery.cpp

moc_xIrcNickActionQuery.cpp: $(MOC) xIrcNickActionQuery.h
	$(MOC) xIrcNickActionQuery.h -o moc_xIrcNickActionQuery.cpp

moc_xIrcNickCombo.cpp: $(MOC) xIrcNickCombo.h
	$(MOC) xIrcNickCombo.h -o moc_xIrcNickCombo.cpp

moc_xIrcNickQuery.cpp: $(MOC) xIrcNickQuery.h
	$(MOC) xIrcNickQuery.h -o moc_xIrcNickQuery.cpp

moc_xIrcNotifyQuery.cpp: $(MOC) xIrcNotifyQuery.h
	$(MOC) xIrcNotifyQuery.h -o moc_xIrcNotifyQuery.cpp

moc_xIrcNotifyTable.cpp: $(MOC) xIrcNotifyTable.h
	$(MOC) xIrcNotifyTable.h -o moc_xIrcNotifyTable.cpp

moc_xIrcPeopleEdit.cpp: $(MOC) xIrcPeopleEdit.h
	$(MOC) xIrcPeopleEdit.h -o moc_xIrcPeopleEdit.cpp

moc_xIrcPeopleTable.cpp: $(MOC) xIrcPeopleTable.h
	$(MOC) xIrcPeopleTable.h -o moc_xIrcPeopleTable.cpp

moc_xIrcServerEdit.cpp: $(MOC) xIrcServerEdit.h
	$(MOC) xIrcServerEdit.h -o moc_xIrcServerEdit.cpp

moc_xIrcServerQuery.cpp: $(MOC) xIrcServerQuery.h
	$(MOC) xIrcServerQuery.h -o moc_xIrcServerQuery.cpp

moc_xIrcServerTable.cpp: $(MOC) xIrcServerTable.h
	$(MOC) xIrcServerTable.h -o moc_xIrcServerTable.cpp

moc_xIrcSocket.cpp: $(MOC) xIrcSocket.h
	$(MOC) xIrcSocket.h -o moc_xIrcSocket.cpp

####### Install

install:  

uninstall:  

